### ISSUE TITLE
text.dm

### ISSUE THREAD

**Issue by PlinHost** [Derven/Aurora_the_cruiser#11]
Содержит бесполезные функции и черную магию.
Заменить на бьендовские `splittext` и `replacetext`.

**Comment by Derven** [comment]
Я чо, зря пиздил чтоле

**Comment by PlinHost** [comment]
Ты на каком кладбище вообще это нашел? Начиная с 510 сплит и реплейс встроены, а конкат хуй пойми что вообще делает
